### ISSUE TITLE
Add known shortcut tasks to extractor configs

### ISSUE THREAD

**Issue by camallen** [zooniverse/aggregation-for-caesar#113]
My use case is to split out the shortcuts from questions and blank data for the PRN downstream consumers. Ideally the extractor config yaml would include which question tasks are shortcut tasks so i can reflect on this information. 

Currently my extractor config looks like
```
extractor_config:
    point_extractor_by_frame:
    -   details:
            T0_tool3:
            - question_extractor
        task: T0
        tools:
        - 0
        - 1
        - 2
        - 3
    question_extractor:
    -   task: T1
    -   task: T2
    -   task: T3
workflow_id: 4958
workflow_version: '17'
```

I was hoping we could add a nested shortcut flag to the `question_extractors`, perhaps something like below. It could also be another root key value `shortcut_questions` that list the shortcut tasks as well. 
```
question_extractor:
    -   task: T1:
           shortcut: true
    -   task: T2
    -   task: T3
           shortcut: true
```

My workflow config looks like this where i've got a drawing task T0 (linked to shortcut T1) and a question task T2 (linked to shortcut T3)
```
{
	"T1": {
		"type": "shortcut",
		"answers": [{
			"label": "Unclassifiable Image"
		}, {
			"label": "Ocean Only (no land)"
		}]
	},
	"T3": {
		"type": "shortcut",
		"answers": [{
			"label": "Unclassifiable Image"
		}, {
			"label": "Ocean Only (no land)"
		}],
		"question": "How many structures are in this image?\n(estimated)"
	}
}
```

**Comment by CKrawczyk** [comment]
Are you looking for the configuration to identify what tasks are the shortcuts or looking for the code to auto-split the shortcut tasks to a separate `csv` file?

The second case can be achieved running the extractor with a config file that only contains the shortcut tasks:
```
extractor_config:
    question_extractor:
    -   task: T1
    -   task: T3
workflow_id: 4958
workflow_version: '17'
```

A similar thing can be can be done with the drawing tools, the extractor will only pull out the tools and tasks listed in the config files.

**Comment by camallen** [comment]
That's good to know and will probably save me some code though i need to handle other cases, like blank data, etc. 

I really just want a way to know which are shortcut tasks from the workflow task JSON blobs, preferably via a config script directive that either spits out a different config file for shortcuts or adds a nested shortcut key under the `question_extractor` key in the extractor config.

**Comment by CKrawczyk** [comment]
The PR above changes the configuration so shortcut tasks are handled with a different extractor and reducer than the question task.  The new config file looks like:
```yaml
extractor_config:
    point_extractor_by_frame:
    -   details:
            T0_tool3:
            - question_extractor
        task: T0
        tools:
        - 0
        - 1
        - 2
        - 3
    question_extractor:
    -   task: T2
    shortcut_extractor:
    -   task: T1
    -   task: T3
workflow_id: 4958
workflow_version: '17.60'
```

And the new shortcut reducer config file looks like:

```yaml
reducer_config:
    shortcut_reducer: {}
```

Note: the just creates an alias points the `shortcut_extractor/reducer` endpoint to the same function the `question_extractor/reducer` uses.
