### ISSUE TITLE
Inconsistent data labels for point tasks vs question tasks

### ISSUE THREAD

**Issue by camallen** [zooniverse/aggregation-for-caesar#115]
I've got some point extracts that i'm standardizing formats for downstream consumption (tPRN use case). I've noticed that question / shortcut tasks have the task answer labels as column headers whereas the point extractor has tool labels. I was expecting the point extractor rows to have column headers like `data.frame0.Road Blockage_x` instead of `data.frame0.T0_tool0_x`.

Subtasks depend on the answer value so they are sparse columns, but i guess `data.frame0.T0_tool3_details` would be `data.frame0.Minor-(less-than-20%-damaged)`

So my question is this on purpose? Or just the way that the point extractors worked out? Will this change? I'd like to keep the downstream format consistent but I'm pretty sure i need the tool labels as column headers to help with data analysis downstream. Any thoughts appreciated.

Dome data examples (apologies for the formatting issues)

Point extractor data example
``` table
classification_id                       redacted
user_name                               redacted
user_id                                      redacted
workflow_id                              4958
task                                           T0
created_at                                 2017-09-13 23:59:34 UTC
subject_id                                  12791408
extractor                                    point_extractor_by_frame
data.aggregation_version         2.1.0
data.frame0.T0_tool0_x            NaN
data.frame0.T0_tool0_y            NaN
data.frame0.T0_tool1_x            NaN
data.frame0.T0_tool1_y            NaN
data.frame0.T0_tool2_x           NaN
data.frame0.T0_tool2_y           NaN
data.frame0.T0_tool3_details   NaN
data.frame0.T0_tool3_x          NaN
data.frame0.T0_tool3_y          NaN
data.frame1.T0_tool0_x          NaN
data.frame1.T0_tool0_y          NaN
data.frame1.T0_tool1_x          NaN
data.frame1.T0_tool1_y          NaN
data.frame1.T0_tool2_x         NaN
data.frame1.T0_tool2_y         NaN
data.frame1.T0_tool3_details   NaN
data.frame1.T0_tool3_x         NaN
data.frame1.T0_tool3_y         NaN
```

Question extractor data example
```
classification_id      redacted
user_name               redacted
user_id                     redacted
workflow_id             4958
task                          T1
created_at                2017-09-23 08:12:58 UTC
subject_id                13157043
extractor                  question_extractor
data.10-to-30          NaN
data.None                NaN
data.aggregation_version 2.0.3
data.more-than-30 NaN
data.none                 NaN
data.up-to-10           NaN
```

Workflow Task labels
``` yaml
T0.instruction: 'Mark the features you see. If you don''t see any, just click "Done" to move on. *If you''re not sure what to do, click the "Need some help with this task?" button below.*'
T0.tools.0.label: Road Blockage
T0.tools.1.label: Flood
T0.tools.2.label: Temporary Settlement
T0.tools.3.details.0.answers.0.label: Minor (less than 20% damaged)
T0.tools.3.details.0.answers.1.label: Moderate (20 - 60% damaged)
T0.tools.3.details.0.answers.2.label: Catastrophic (more than 60% damaged)
T0.tools.3.details.0.question: 'How severe is the damage? *(to see examples, please check the Field Guide)*'
T0.tools.3.label: Structural damage
T1.answers.0.label: Unclassifiable Image
T1.answers.1.label: Ocean Only (no land)
T2.answers.0.label: None
T2.answers.1.label: Up to 10
T2.answers.2.label: 10 to 30
T2.answers.3.label: More than 30
T2.question: "**Approximately** how many structures are shown in the subject? \n\n\
    Please include non-temporary structures from the **Before** image as well as any\
    \ temporary structures in the **After** image. \n\nChoose the answer that best\
    \ represents your estimate. "
T3.answers.0.label: Unclassifiable Image
T3.answers.1.label: Ocean Only (no land)
T3.question: 'How many structures are in this image? (estimated)'
```
