### ISSUE TITLE
Missing task in reducer file (Shape reduction with text)

### ISSUE THREAD

**Issue by mclenard** [zooniverse/aggregation-for-caesar#280]
Hello,
I'm working on a project that involves text transcription using the shape tools. Recently, we changed the workflow we're using to account for two different categories of data, so we split these two categories into their own task (T1 and T4). However, when I went to try out aggregation for this new workflow, it seems that the reducer config file is being generated only recognizing one of the two tasks (T4), so text is only being aggregated for one type of data. I attempted to manually adjust the .yaml file to account for T1 as well, but I don't think I was constructing it correctly. I would really appreciate if you could take a quick look at this and let me know what's going on, and if I'm doing something incorrectly. Thanks!

Workflow ID: 13717
Version: 1.24

[Extractor_config_workflow_13717_V1.24.txt](https://github.com/zooniverse/aggregation-for-caesar/files/4431830/Extractor_config_workflow_13717_V1.24.txt)
[Reducer_config_workflow_13717_V1.24_shape_extractor_rectangle.txt](https://github.com/zooniverse/aggregation-for-caesar/files/4431831/Reducer_config_workflow_13717_V1.24_shape_extractor_rectangle.txt)
[tar-pits-zooniverse-project-workflows.xlsx](https://github.com/zooniverse/aggregation-for-caesar/files/4431832/tar-pits-zooniverse-project-workflows.xlsx)

**Comment by CKrawczyk** [comment]
Hmm, I see the issue.  The reducer config is saving both configs to the same file name since they both use the same kind of extractor.  Looking at this a bit more closely this kind of workflow setup is an edge case where the auto-config is going to fail all around. I.e. it can't handle multiple drawing tasks of the same shape that each have sub-tasks.

Here you are going to be better off making two different extractor configs, one for each task, and two reducer configs, again one for each task.  For this case the setups will look like:

# Task T1

## Extractor yaml
```yaml
extractor_config:
    shape_extractor_rectangle:
    -   details:
            T1_tool0:
            - text_extractor
            - text_extractor
            - text_extractor
            - text_extractor
            - text_extractor
            - text_extractor
            - text_extractor
            - text_extractor
        shape: rectangle
        task: T1
        tools:
        - 0
workflow_id: 13717
workflow_version: '1.24'
```

## Reducer yaml
```yaml
reducer_config:
    shape_reducer_dbscan:
        details:
            T1_tool0:
            - text_reducer
            - text_reducer
            - text_reducer
            - text_reducer
            - text_reducer
            - text_reducer
            - text_reducer
            - text_reducer
        shape: rectangle
```


# Task T4
## Extractor yaml
```yaml
extractor_config:
    shape_extractor_rectangle:
    -   details:
            T4_tool0:
            - text_extractor
            - text_extractor
            - text_extractor
            - text_extractor
            - text_extractor
            - text_extractor
            - text_extractor
        shape: rectangle
        task: T4
        tools:
        - 0
workflow_id: 13717
workflow_version: '1.24'
```

## Reducer yaml
```yaml
reducer_config:
    shape_reducer_dbscan:
        details:
            T4_tool0:
            - text_reducer
            - text_reducer
            - text_reducer
            - text_reducer
            - text_reducer
            - text_reducer
            - text_reducer
        shape: rectangle
```

Just run the extractor two times, once with each of the confgs listed above.  This will make to extract `csv` files, one for each task.  Pass these into the reducer with the correct config above to get you reductions.

Let me know if you need help parsing the resulting reduction files, sub-tasks are a bit confusing as it is currently implemented, I am looking to make this cleaner in the future (some time in the next few months).

**Comment by mclenard** [comment]
Thanks! This works. I wouldn't have been able to figure this one out on my own! One follow-up question: When I try to supply some parameters for DBSCAN, to make use of the consensus text clustering feature for our transcription data, it gives me a KeyError:

```
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\panoptes_aggregation.exe\__main__.py", line 7, in <module>
  File "c:\python\lib\site-packages\panoptes_aggregation\scripts\aggregation_parser.py", line 287, in main
    panoptes_aggregation.scripts.reduce_csv(
  File "c:\python\lib\site-packages\panoptes_aggregation\scripts\reduce_panoptes_csv.py", line 193, in reduce_csv
    reduced_data_list = reduce_subject(
  File "c:\python\lib\site-packages\panoptes_aggregation\scripts\reduce_panoptes_csv.py", line 58, in reduce_subject
    reduction = reducers.reducers[reducer_name](data, user_id=user_ids, **keywords)
  File "c:\python\lib\site-packages\panoptes_aggregation\reducers\reducer_wrapper.py", line 54, in wrapper
    reduction = func(data, **kwargs_data, **kwargs_details, **kwargs_extra_data)
  File "c:\python\lib\site-packages\panoptes_aggregation\reducers\subtask_reducer_wrapper.py", line 36, in wrapper
    detail_reduced.append(reducer(detail, no_version=True))
  File "c:\python\lib\site-packages\panoptes_aggregation\reducers\reducer_wrapper.py", line 42, in wrapper
    kwargs_extra_data['user_id'] = kwargs['user_id']
KeyError: 'user_id'
```

In an older workflow, before we split up the transcriptions into two tasks, I managed to get the DBSCAN clustering to work fine, so I'm not sure why it's throwing an error now. Do you know what the issue might be? Thanks a bunch!

**Comment by CKrawczyk** [comment]
Hmmm, that is odd.  The DBSCAN params should be at the same indent level as `shape` and `details` in the yaml files.

That error is saying that the `user_id` column is not being passed along from the extract to the reducer, this is something that is done automatically.  Also it passes this info along regardless of what params are given in the yaml file.

Testing on my end I was able to use the following reducer config without issue:
```yaml
reducer_config:
    shape_reducer_dbscan:
        eps: 5
        min_samples: 2
        details:
            T4_tool0:
            - text_reducer
            - text_reducer
            - text_reducer
            - text_reducer
            - text_reducer
            - text_reducer
            - text_reducer
        shape: rectangle
```
